In [2]:
# import necessary libraries priorly, the other libraries will be imported on their respective section
import pandas as pd
import numpy as np
import matplotlib as plt
import sklearn

In [5]:
# the dataset was uploaded to a github account to facilitate the calling process. thus, this link refers to raw format of data directly
# this eliminated the need to call the data from local direcotyr all the time
data_url = "https://raw.githubusercontent.com/mrzeynalli/credit_score_project/main/Dataset/bank_customers_data.csv"

# read csv file and turn into a dataframe object
data = pd.read_csv(data_url)

# display first 10 rows of the dataframe
data.head(10)

C:\Users\ezeyn\AppData\Local\Temp\ipykernel_10260\1030747455.py:6: DtypeWarning: Columns (52,53) have mixed types. Specify dtype option on import or set low_memory=False.
  data = pd.read_csv(data_url)

,Unnamed: 0,ID_CLIENT,CLERK_TYPE,PAYMENT_DAY,APPLICATION_SUBMISSION_TYPE,QUANT_ADDITIONAL_CARDS,POSTAL_ADDRESS_TYPE,SEX,MARITAL_STATUS,QUANT_DEPENDANTS,...,FLAG_HOME_ADDRESS_DOCUMENT,FLAG_RG,FLAG_CPF,FLAG_INCOME_PROOF,PRODUCT,FLAG_ACSP_RECORD,AGE,RESIDENCIAL_ZIP_3,PROFESSIONAL_ZIP_3,TARGET_LABEL_BAD=1
0,0,1,C,5,Web,0,1,F,6,1,...,0,0,0,0,1,N,32,595,595,1
1,1,2,C,15,Carga,0,1,F,2,0,...,0,0,0,0,1,N,34,230,230,1
2,2,3,C,5,Web,0,1,F,2,0,...,0,0,0,0,1,N,27,591,591,0
3,3,4,C,20,Web,0,1,F,2,0,...,0,0,0,0,1,N,61,545,545,0
4,4,5,C,10,Web,0,1,M,2,0,...,0,0,0,0,1,N,48,235,235,1
5,5,6,C,10,0,0,1,M,2,0,...,0,0,0,0,2,N,40,371,371,1
6,6,7,C,15,Carga,0,1,F,2,2,...,0,0,0,0,1,N,40,413,413,1
7,7,8,C,25,Web,0,1,F,1,0,...,0,0,0,0,1,N,28,686,686,0
8,8,9,C,15,0,0,1,F,1,0,...,0,0,0,0,2,N,31,172,172,0
9,9,10,C,5,0,0,1,F,1,0,...,0,0,0,0,1,N,41,914,914,0

In [11]:
# print the number of rows and columns
print(f'Dataset has {data.shape[0]} rows and {data.shape[1]} columns\n')

# print the list of columns
print(f'The list of columns are: {list(data.columns)}')

Dataset has 50000 rows and 55 columns

The list of columns are: ['Unnamed: 0', 'ID_CLIENT', 'CLERK_TYPE', 'PAYMENT_DAY', 'APPLICATION_SUBMISSION_TYPE', 'QUANT_ADDITIONAL_CARDS', 'POSTAL_ADDRESS_TYPE', 'SEX', 'MARITAL_STATUS', 'QUANT_DEPENDANTS', 'EDUCATION_LEVEL', 'STATE_OF_BIRTH', 'CITY_OF_BIRTH', 'NACIONALITY', 'RESIDENCIAL_STATE', 'RESIDENCIAL_CITY', 'RESIDENCIAL_BOROUGH', 'FLAG_RESIDENCIAL_PHONE', 'RESIDENCIAL_PHONE_AREA_CODE', 'RESIDENCE_TYPE', 'MONTHS_IN_RESIDENCE', 'FLAG_MOBILE_PHONE', 'FLAG_EMAIL', 'PERSONAL_MONTHLY_INCOME', 'OTHER_INCOMES', 'FLAG_VISA', 'FLAG_MASTERCARD', 'FLAG_DINERS', 'FLAG_AMERICAN_EXPRESS', 'FLAG_OTHER_CARDS', 'QUANT_BANKING_ACCOUNTS', 'QUANT_SPECIAL_BANKING_ACCOUNTS', 'PERSONAL_ASSETS_VALUE', 'QUANT_CARS', 'COMPANY', 'PROFESSIONAL_STATE', 'PROFESSIONAL_CITY', 'PROFESSIONAL_BOROUGH', 'FLAG_PROFESSIONAL_PHONE', 'PROFESSIONAL_PHONE_AREA_CODE', 'MONTHS_IN_THE_JOB', 'PROFESSION_CODE', 'OCCUPATION_TYPE', 'MATE_PROFESSION_CODE', 'EDUCATION_LEVEL.1', 'FLAG_HOME_ADDRESS_DOCUMENT', 'FLAG_RG', 'FLAG_CPF', 'FLAG_INCOME_PROOF', 'PRODUCT', 'FLAG_ACSP_RECORD', 'AGE', 'RESIDENCIAL_ZIP_3', 'PROFESSIONAL_ZIP_3', 'TARGET_LABEL_BAD=1']

In [47]:
# some columns are unnecceesarry, given that their encoding are not provided. adress related columns are also unnecessary.
# the below list contains the columns that need to be dropped (to be discussed with peers later)
columns_to_be_kept = ['PAYMENT_DAY',  'SEX', 'MARITAL_STATUS', 'QUANT_DEPENDANTS', 'EDUCATION_LEVEL', 'NACIONALITY', 
'PERSONAL_MONTHLY_INCOME', 'OTHER_INCOMES','PERSONAL_ASSETS_VALUE', 'COMPANY', 'MONTHS_IN_THE_JOB','EDUCATION_LEVEL.1', 
'PRODUCT', 'FLAG_ACSP_RECORD', 'AGE', 'TARGET_LABEL_BAD=1']

,Unnamed: 0,ID_CLIENT,CLERK_TYPE,PAYMENT_DAY,APPLICATION_SUBMISSION_TYPE,QUANT_ADDITIONAL_CARDS,POSTAL_ADDRESS_TYPE,SEX,MARITAL_STATUS,QUANT_DEPENDANTS,...,FLAG_HOME_ADDRESS_DOCUMENT,FLAG_RG,FLAG_CPF,FLAG_INCOME_PROOF,PRODUCT,FLAG_ACSP_RECORD,AGE,RESIDENCIAL_ZIP_3,PROFESSIONAL_ZIP_3,TARGET_LABEL_BAD=1
4364,4364,4365,C,10,Web,0,1,M,2,3,...,0,0,0,0,1,N,40,384,384,0
18725,18725,18726,C,10,Web,0,1,M,2,0,...,0,0,0,0,1,N,69,785,785,0
24672,24672,24673,C,10,Web,0,1,M,2,1,...,0,0,0,0,1,N,71,384,384,0
25785,25785,25786,C,20,Web,0,1,M,2,1,...,0,0,0,0,1,N,56,384,384,0
31243,31243,31244,C,10,Web,0,1,F,4,0,...,0,0,0,0,1,N,59,785,785,0